### ISSUE TITLE
Incorrectly identifies avif image file as "video/quicktime"

### ISSUE THREAD

**Issue by rjgotten** [drewnoakes/metadata-extractor-dotnet#347]
The library incorrectly identifies AVIF image files as AV1 videos with MIME content type "video/quicktime" rather than the correct "image/avif".

Additionally the content type "video/quicktime" is incorrect.
The standardized content type for AV1 video is "video/AV1": https://www.iana.org/assignments/media-types/video/AV1

The definition of that media type is strictly speaking limited to video-streaming via RTP and is not defined for other uses, but it makes more sense than "video/quicktime" which is just an opaque box of 'anything Apple Quicktime can play back.'

It's akin to speccing MP4 videos as "video/-x-msvideo," because Windows Media Player can play it back.

**Comment by StefanOltmann** [comment]
It's not really incorrect.

AVIF is based on HEIF, which is a ISO Base Media File Format (BMFF). This originated from QuickTime. So in fact it's a QuickTime file somehow. ;)

The fix is just to use the already implemented HEIC logic for AVIF files.

I just did that for the Java version:
https://github.com/drewnoakes/metadata-extractor/pull/649

**Comment by StefanOltmann** [comment]
Resolved by #396 now. :)
