### ISSUE TITLE
Excessive bounds checking when reading multi-byte values

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor-dotnet#62]
For example, `ByteArrayReader.GetInt32` validates the index for four bytes. It then calls `GetByte` four times, which causes a further four validations.

One potential solution is to have a non-public `GetByteInternal` method that doesn't validate.

Investigate at the same time whether we can have the `GetByte` calls be inlined. Being virtual probably nixes that.

**Comment by twest820** [comment]
Approaches in the direction of `BitConverter.ToInt32(GetBytes(index, 4))` with `Array.Reverse()` or such for endianness might be worth a look. I haven't profiled this space much as I'm usually working with SIMD intrinsics for such things I but recall finding they're faster than shifts, presumably because it's C# for reinterpret_cast<>. In general, among the various reader classes I've looked at, it appears to me shifting to a more conventional offset + length approach for indexing into a byte[] might be beneficial. In particular, it moves the GetBytes() contract away from having to copy to a new byte[]. However, making much of this performant is contingent on the reader's maintaining it's own byte[] buffer.

Virtual calls can be inlined when the compiler knows it's dealing with a sealed type. Haven't looked to see if this actually happens, but it's a pretty niche optimization regardless.
