### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by cestes001** [drewnoakes/metadata-extractor-dotnet#63]
I keep getting "Access Denied" error on the folder, imagePath.  The folder and those above and below are have Administrator given full access.  

the form_load handler is listed below:

        private void Form1_Load(object sender, EventArgs e)
        {
            string imagePath = "E:\\Lightroom\\_Reduced\\For Web";
                try
                {
                IEnumerable<MetadataExtractor.Directory> directories = ImageMetadataReader.ReadMetadata(imagePath);

            }
            catch (UnauthorizedAccessException ex)
                {
                throw new UnauthorizedAccessException  (ex.Message);
                }
           }
    }

**Comment by drewnoakes** [comment]
The user under whom your process is running must not have access to that path. This doesn't sound like an issue with MetadataExtractor.

If you open a `FileStream` and pass that instead, you'll likely see the exception occurs when opening the stream, not in this library.

I'll close this as I don't think it's a bug in the library, but something about your environment. If you determine otherwise, I'll reopen.

**Comment by cestes001** [comment]
System.IO.FileInfo[] files = null;
System.IO.DirectoryInfo[] subDirs = null;

With these two, I'm able to recursively step through every file and folder on the E Drive, including the one to which access is denied.

Here's the app.config file.  Does this lend any hints as to the cause?
[App.zip](https://github.com/drewnoakes/metadata-extractor-dotnet/files/546569/App.zip)

**Comment by drewnoakes** [comment]
I'm not familiar with `System.Configuration.UserSettingsGroup`. You could try checking `Environment.UserName` in your code to see who your program is running as.

This is a general question so you might get a more expert audience on Stack Overflow.
