### ISSUE TITLE
ReadMetadata throw folder in shared network give an error credentials

### ISSUE THREAD

**Issue by jespicas** [drewnoakes/metadata-extractor-dotnet#86]
If you use ReadMetadata and the folder is on shard network, shown an credentials error.

An unhandled exception of type 'System.UnauthorizedAccessException' occurred in mscorlib.dll

ReadMetadata not have any implemented method to pass a credentials or impersonate.

**Comment by drewnoakes** [comment]
I don't think this problem is specific to MetadataExtractor. If you can open a stream in your own code, then ReadMetadata can use that stream.

If you can't open the FileStream in the first place, then it's a more general question. I don't know much about this, and suggest looking on Stack Overflow where it's likely been asked before a few times.

Another option would be to mount the `\\server\path` to a local drive (eg: `x:\`) and access it that way.

Closing this. If you still think it's a bug in MetadataExtractor then please provide more details. Thanks.

**Comment by jespicas** [comment]
Sorry,
OK not is a bug, the problem is related with filestream.

**Comment by drewnoakes** [comment]
No problem. Good luck.
